tasks:
  - init: apt-get update && apt-get install git ffmpeg libsm6 libxext6 libgl1-mesa-glx -y && pip install -r requirements.txt
    command: PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128 DEFAULT_NUM_IMAGES=1 SHARE=true ENABLE_REFINER=false python app.py
